#!/bin/bash

#
# Generic template for bash scripts
#

set -u    # Die if trying to access variables that are undefined
set -e    # Exit if any command has a non-zero return value

DATE=$(date +%Y%m%d%H%M%S)
ORIG_DIR=$(pwd)
SCRPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

main() {
    cd ${SCRPT_DIR}

    # Main logic goes here

    cd ${ORIG_DIR} >/dev/null
}

main
