# Persistent iptables / ip6tables rules.

RULES_V4="/etc/iptables/rules.v4"
RULES_V6="/etc/iptables/rules.v6"

render_rules_v4() {
    local out=$1
    local cidr

    cat > "${out}" <<'EOF'
# Generated by linux_cfgs setup_security/install
*filter
:INPUT DROP [0:0]
:FORWARD DROP [0:0]
:OUTPUT ACCEPT [0:0]
EOF

    echo "-A INPUT -i lo -j ACCEPT" >> "${out}"
    echo "-A INPUT -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT" >> "${out}"
    for cidr in "${ALLOWED_CIDRS[@]}"; do
        echo "-A INPUT -s ${cidr} -j ACCEPT" >> "${out}"
    done
    echo '-A INPUT -m limit --limit 5/min -j LOG --log-prefix "iptables denied: " --log-level 4' >> "${out}"
    echo "-A INPUT -j DROP" >> "${out}"
    echo "COMMIT" >> "${out}"
}

render_rules_v6() {
    local out=$1

    cat > "${out}" <<'EOF'
# Generated by linux_cfgs setup_security/install
*filter
:INPUT DROP [0:0]
:FORWARD DROP [0:0]
:OUTPUT ACCEPT [0:0]
EOF

    if [[ ${SECURITY_IPV6_POLICY} == "accept_established" ]]; then
        echo "-A INPUT -i lo -j ACCEPT" >> "${out}"
        echo "-A INPUT -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT" >> "${out}"
        for cidr in "${ALLOWED_CIDRS[@]}"; do
            echo "-A INPUT -s ${cidr} -j ACCEPT" >> "${out}"
        done
    fi

    echo '-A INPUT -m limit --limit 5/min -j LOG --log-prefix "ip6tables denied: " --log-level 4' >> "${out}"
    echo "-A INPUT -j DROP" >> "${out}"
    echo "COMMIT" >> "${out}"
}

setup_iptables() {
    local iptables_bkp_root tmp_v4 tmp_v6

    [[ ${SKIP_FIREWALL} -eq 0 ]] || return 0

    iptables_bkp_root="${BKP_DIR}/iptables"
    run mkdir -p "${iptables_bkp_root}"
    if [[ ${DRY_RUN} -eq 0 ]]; then
        iptables-save > "${iptables_bkp_root}/ip4tables_bkup_${DATE}.txt"
        ip6tables-save > "${iptables_bkp_root}/ip6tables_bkup_${DATE}.txt"
    fi
    log "Backed up live iptables rules to ${iptables_bkp_root}/ip*tables_bkup_${DATE}.txt"

    export DEBIAN_FRONTEND=noninteractive
    run apt-get install -y iptables-persistent

    tmp_v4="$(mktemp)"
    tmp_v6="$(mktemp)"
    render_rules_v4 "${tmp_v4}"
    render_rules_v6 "${tmp_v6}"

    if [[ ${DRY_RUN} -eq 1 ]]; then
        log "[dry-run] would install rules:"
        cat "${tmp_v4}"
        cat "${tmp_v6}"
        rm -f "${tmp_v4}" "${tmp_v6}"
        return 0
    fi

    run mkdir -p /etc/iptables
    install -m 644 "${tmp_v4}" "${RULES_V4}"
    install -m 644 "${tmp_v6}" "${RULES_V6}"
    rm -f "${tmp_v4}" "${tmp_v6}"

    iptables-restore < "${RULES_V4}"
    ip6tables-restore < "${RULES_V6}"

    if command -v netfilter-persistent >/dev/null 2>&1; then
        run netfilter-persistent save
    fi

    log "Installed persistent firewall rules in ${RULES_V4} and ${RULES_V6}."
}
